
export const defaultColleges = [
    { value: "1", label: "College of Accountancy and Finance" },
    { value: "2", label: "College of Architecture, Design and the Built Environment" },
    { value: "3", label: "College of Business Administration" },
    { value: "4", label: "College of Computer and Information Sciences" },
    { value: "5", label: "College of Engineering" },
    { value: "6", label: "College of Human Kinetics" },
    { value: "7", label: "College of Law" },
    { value: "8", label: "College of Communication" },
    { value: "9", label: "College of Education" },
    { value: "10", label: "College of Political Science and Public Administration" },
    { value: "11", label: "College of Science" },
    { value: "12", label: "College of Tourism, Hospitality and Transportation Management" },
    { value: "13", label: "Graduate School" },
    { value: "14", label: "Institute of Technology" },
    { value: "15", label: "PUP Laboratory Highschool" },
    { value: "16", label: "PUP Senior Highschool" },
    { value: "17", label: "College of Social Sciences and Development" },
  ];