export const events = [
    {
        id: '1',
        name: "Cisco PUP Connect Year-End Party 2024",
        host: "Cisco PUP Connect",
        description: "Celebrate the year-end with fun, games, and prizes!",
        category: "Uni-wide",
        followers: 200,
        imageSrc: "./src/sample_data/sample_orgs/gdg_circle.png",
        price: 100,
        start_date: new Date('2024-12-20T18:00:00'),
        end_date: new Date('2024-12-20T23:59:59'),
        start_time: "18:00",
        end_time: "20:00",
    },
    {
        id: '2',
        name: "PUP CCIS Student Council TFT Tournament",
        host: "CCIS Student Council",
        description: "Registration for the Liga Republika 2024 Open Qualifiers is now live!  The competition begins in July with 4 weekly qualifiers accommodating up to 512 teams per week. They will be competing in 7 rounds of single-elimination battles and the top 3 from each week will secure their spots to the group stage.  Open qualifiers will be held every week on July 13, July 20, July 27, and August 2...",
        category: "University Event",
        followers: 500,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
        price: 0,
        start_date: new Date('2024-01-15T09:00:00'),
        end_date: new Date('2024-01-15T17:00:00'),
        start_time: "09:00",
        end_time: "17:00",
    },
    {
        id: '3',
        name: "Tech Innovation Summit",
        host: "PUP Computer Society",
        description: "Explore the latest trends in tech innovation.",
        category: "University Event",
        followers: 500,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
        price: 0,
        start_date: new Date('2024-02-20T09:00:00'),
        end_date: new Date('2024-02-20T17:00:00'),
        start_time: "09:00",
        end_time: "17:00",
    },
    {
        id: '4',
        name: "Tech Innovation Summit",
        host: "PUP Computer Society",
        description: "Explore the latest trends in tech innovation.",
        category: "University Event",
        followers: 500,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
        price: 0,
        start_date: new Date('2024-03-10T09:00:00'),
        end_date: new Date('2024-03-10T17:00:00'),
        start_time: "09:00",
        end_time: "17:00",
    },
    {
        id: '5',
        name: "Tech Innovation Summit",
        host: "PUP Computer Society",
        description: "Explore the latest trends in tech innovation. lorem ipsum dolor est",
        category: "University Event",
        followers: 5001,
        imageSrc: "./src/sample_data/sample_orgs/cisco_connect.jpg",
        price: 10000,
        start_date: new Date('2024-04-05T09:00:00'),
        end_date: new Date('2024-04-05T17:00:00'),
        start_time: "09:00",
        end_time: "17:00",
    },
    {
        id: '6',
        name: "Tech Innovation Summit",
        host: "PUP Computer Society",
        description: "Explore the latest trends in tech innovation. lorem ipsum dolor est",
        category: "University Event",
        followers: 5001,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
        price: 10000,
        start_date: new Date('2024-05-10T09:00:00'),
        end_date: new Date('2024-05-10T17:00:00'),
        start_time: "09:00",
        end_time: "17:00",
    },
];



export const orgs = [
    {
        name: "AWS Cloud Club PUP",
        description: "Learn cloud computing with AWS Cloud Club.",
        category: "Tech Organization",
        followers: 3000,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
    },
    {
        name: "Creative Arts Club",
        description: "Express your creativity through arts and crafts.",
        category: "Arts Organization",
        followers: 150,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
    },
    {
        name: "Squid Game Club",
        description: "Express your creativity through arts and crafts.",
        category: "Arts Organization",
        followers: 150,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
    },
    {
        name: "Philippine Society of Information Technology Students",
        description: "Express your creativity through arts and crafts.",
        category: "Arts Organization",
        followers: 150,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
    },
    {
        name: "PUP Suntukan Society",
        description: "Express your creativity through arts and crafts.",
        category: "Arts Organization",
        followers: 150,
        imageSrc: "./src/sample_data/sample_orgs/awscc_circle.png",
    },
];
